package org.learning.by.example.reactive.kotlin.microservices.KotlinReactiveMS.application

import org.springframework.boot.autoconfigure.SpringBootApplication

@SpringBootApplication
class KotlinReactiveMsApplication